# Generated by Django 2.1.1 on 2018-10-08 18:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of classification.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of movement', max_length=50)),
                ('description', models.CharField(help_text='Movement description.', max_length=1000)),
                ('type', models.CharField(blank=True, choices=[('m', 'Isometric'), ('i', 'Isotonic'), ('c', 'Cardiovascular')], help_text='Exercise catagory', max_length=20)),
                ('video', models.URLField(help_text='Video demonstrating exercise.', max_length=500)),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Back', 'Back'), ('Chest', 'Chest'), ('Arms', 'Arms'), ('Legs', 'Legs')], help_text='name of body area', max_length=20)),
                ('muscle', models.CharField(help_text='name of body area', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=0)),
                ('time', models.DateField(blank=True, null=True)),
                ('reps', models.ManyToManyField(to='tracker.Reps')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseinstance',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Sets'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(to='tracker.MuscleGroup'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='progression',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Exercise'),
        ),
    ]
