# Generated by Django 2.1.1 on 2018-09-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('b', 'Back'), ('c', 'Chest'), ('a', 'Arms'), ('l', 'Legs')], help_text='name of body area', max_length=1)),
                ('muscle', models.CharField(help_text='name of body area', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='BodySegment',
        ),
        migrations.AlterField(
            model_name='classification',
            name='segment',
            field=models.ManyToManyField(help_text='body segments\n                                     affected by the exercise.', to='tracker.MuscleGroup'),
        ),
    ]
