# Generated by Django 2.1.1 on 2018-09-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180910_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroup',
            name='muscle',
            field=models.CharField(help_text='name of body area', max_length=50),
        ),
    ]
