# Generated by Django 2.1.1 on 2018-09-10 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180910_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.MuscleGroup'),
        ),
    ]
