# Generated by Django 2.1.1 on 2018-09-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180910_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroup',
            name='muscle_group',
            field=models.CharField(choices=[('Back', 'Back'), ('Chest', 'Chest'), ('Arms', 'Arms'), ('Legs', 'Legs')], help_text='name of body area', max_length=20),
        ),
    ]
