# Generated by Django 2.1.1 on 2018-09-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180910_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='section',
            new_name='classification',
        ),
    ]
