# Generated by Django 2.1.1 on 2018-09-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_classification_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(help_text='Movement description.', max_length=1000),
        ),
    ]
