# Generated by Django 2.1.1 on 2018-09-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20180910_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscle',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(to='tracker.MuscleGroup'),
        ),
    ]
