# Generated by Django 2.2.dev20181018221850 on 2018-10-20 18:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_measurement.models
import measurement.measures.distance
import measurement.measures.mass
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of classification.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of movement', max_length=50)),
                ('description', models.CharField(help_text='Movement description.', max_length=1000)),
                ('type', models.CharField(blank=True, choices=[('m', 'Isometric'), ('i', 'Isotonic'), ('c', 'Cardiovascular')], help_text='Exercise catagory', max_length=20)),
                ('video', models.URLField(help_text='Video demonstrating exercise.', max_length=500)),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Back', 'Back'), ('Chest', 'Chest'), ('Arms', 'Arms'), ('Legs', 'Legs')], help_text='name of body area', max_length=20)),
                ('muscle', models.CharField(help_text='name of body area', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('_height', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance)),
                ('_weight', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('bmi', models.FloatField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('time_zone', models.CharField(default='UTC', max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=0)),
                ('time', models.DateField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, default=0, null=True)),
                ('bpm', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('reps', models.ManyToManyField(to='tracker.Reps')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.DateField(blank=True, help_text='Total exercise time', null=True)),
                ('mood', models.CharField(blank=True, choices=[('e', 'Energetic'), ('s', 'Sleep Deprived'), ('m', 'Motivated'), ('d', 'Demotivated'), ('u', 'Uninterested')], max_length=40, null=True)),
                ('fatigued', models.NullBooleanField(help_text='Whether you feel the muscles involved are fatigued/tired')),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Exercise')),
                ('participant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Profile')),
                ('sets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Sets')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Profile'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(to='tracker.MuscleGroup'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='progression',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Exercise'),
        ),
    ]
