# Generated by Django 2.1.2 on 2018-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20181028_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
