# Generated by Django 2.1.2 on 2018-11-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20181104_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='_distance',
        ),
        migrations.RemoveField(
            model_name='set',
            name='_weight',
        ),
    ]
