# Generated by Django 2.1.2 on 2018-11-04 22:57

from django.db import migrations
import django_measurement.models
import measurement.measures.distance
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20181104_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='_distance',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.distance.Distance),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='_weight',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.mass.Mass),
            preserve_default=False,
        ),
    ]
