# Generated by Django 2.1.2 on 2018-11-04 23:04

from django.db import migrations
import django_measurement.models
import measurement.measures.distance
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20181104_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='_distance',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.distance.Distance),
        ),
        migrations.AlterField(
            model_name='set',
            name='_weight',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.mass.Mass),
        ),
    ]
