# Generated by Django 2.1.2 on 2018-11-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20181104_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='distance_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
